apiVersion: argoproj.io/v1alpha1
kind: CronWorkflow
metadata:
  name: cronwf-xetra
  namespace: argo
spec:
  schedule: "0 * * * 6"
  concurrencyPolicy: "Forbid"
  startingDeadlineSeconds: 70
  workflowSpec:
    entrypoint: dag-template
    serviceAccountName: argo
    volumes:
    - name: config
      configMap:
        name: xetra-config
    templates:
    - name: dag-template
      dag:
        tasks:
        - name: xetra-etl-report1
          template: task-template
  
    - name: task-template
      script:
        image: schwarzl87/xetra-etl:1.0
        imagePullPolicy: Always
        command: [bash]
        source: |
          python /code/run.py /code/configs/xetra-config
        volumeMounts:
        - name: config
          mountPath: /code/configs
          readOnly: true
        env:
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: xetra-secrets
              key: AWS_ACCESS_KEY_ID
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: xetra-secrets
              key: AWS_SECRET_ACCESS_KEY
          